// prisma/seed.cjs
const { PrismaClient } = require("@prisma/client");
const bcrypt = require("bcryptjs");

const prisma = new PrismaClient();

// 🌴 Données des propriétés
const properties = [
  {
    id: "1",
    name: "Villa Lagon Bleu",
    type: "villa",
    city: "Sada",
    region: "Mayotte",
    address: "123 Rue de la Plage, Sada 97610",
    price: 150,
    rentalType: "saisonniere",
    rating: 4.8,
    reviews: 24,
    image: "/tropical-villa-with-pool.jpg",
    description: "Magnifique villa avec piscine et vue sur le lagon",
    bedrooms: 3,
    bathrooms: 2,
    amenities: JSON.stringify(["Piscine", "WiFi", "Climatisation", "Cuisine équipée"]),
  },
  {
    id: "2",
    name: "Appartement T2 Saint-Denis",
    type: "t2",
    city: "Saint-Denis",
    region: "La Réunion",
    address: "456 Avenue de la République, Saint-Denis 97400",
    price: 800,
    rentalType: "longue-duree",
    rating: 4.5,
    reviews: 18,
    image: "/modern-apartment-interior.jpg",
    description: "Appartement moderne en centre-ville",
    bedrooms: 2,
    bathrooms: 1,
    amenities: JSON.stringify(["WiFi", "Climatisation", "Balcon", "Parking"]),
  },
  {
    id: "3",
    name: "Studio Tropical",
    type: "studio",
    city: "Saint-Paul",
    region: "La Réunion",
    address: "789 Rue de la Mer, Saint-Paul 97411",
    price: 60,
    rentalType: "saisonniere",
    rating: 4.6,
    reviews: 32,
    image: "/cozy-studio-apartment.jpg",
    description: "Studio cosy près de la plage",
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Cuisine", "Terrasse", "Vue mer"],
  },
  {
    id: "4",
    name: "Maison Guadeloupe",
    type: "maison",
    city: "Sainte-Anne",
    region: "Guadeloupe",
    address: "321 Chemin du Littoral, Sainte-Anne 97160",
    price: 120,
    rentalType: "saisonniere",
    rating: 4.7,
    reviews: 21,
    image: "/caribbean-house-garden.jpg",
    description: "Maison avec jardin tropical et piscine",
    bedrooms: 4,
    bathrooms: 2,
    amenities: ["Piscine", "Jardin", "Cuisine", "Terrasse"],
  },
  {
    id: "5",
    name: "Chalet Suisse",
    type: "chalet",
    city: "Crans-Montana",
    region: "Suisse",
    address: "654 Route de la Montagne, Crans-Montana 3963",
    price: 200,
    rentalType: "saisonniere",
    rating: 4.9,
    reviews: 45,
    image: "/alpine-chalet-mountains.jpg",
    description: "Chalet 4 étoiles avec vue panoramique",
    bedrooms: 5,
    bathrooms: 3,
    amenities: ["Cheminée", "Sauna", "Terrasse", "Vue montagne"],
    featured: true,
  },
  {
    id: "6",
    name: "Appartement Paris",
    type: "t3",
    city: "Paris",
    region: "France",
    address: "987 Boulevard Saint-Germain, Paris 75006",
    price: 1200,
    rentalType: "longue-duree",
    rating: 4.4,
    reviews: 15,
    image: "/parisian-apartment-elegant.jpg",
    description: "Bel appartement dans le 6ème arrondissement",
    bedrooms: 3,
    bathrooms: 1,
    amenities: ["Ascenseur", "Chauffage", "Balcon", "Proche métro"],
  },
  {
    id: "7",
    name: "Mobile Home Luxe",
    type: "mobile-home",
    city: "Le Gosier",
    region: "Guadeloupe",
    address: "111 Allée des Palmiers, Le Gosier 97190",
    price: 85,
    rentalType: "saisonniere",
    rating: 4.3,
    reviews: 12,
    image: "/luxury-mobile-home-resort.jpg",
    description: "Mobile home moderne avec tous les équipements",
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Climatisation", "Cuisine", "Terrasse", "Parking"],
  },
  {
    id: "8",
    name: "T1 Luxembourg",
    type: "t1",
    city: "Hollerich",
    region: "Luxembourg",
    address: "222 Rue de la Gare, Hollerich L-1627",
    price: 900,
    rentalType: "longue-duree",
    rating: 4.5,
    reviews: 8,
    image: "/modern-studio-apartment.jpg",
    description: "Studio moderne en centre-ville",
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Climatisation", "Parking", "Ascenseur"],
  },
  {
    id: "9",
    name: "Villa Prestige Mayotte",
    type: "villa",
    city: "Mamoudzou",
    region: "Mayotte",
    address: "45 Rue du Lagon, Mamoudzou 97600",
    price: 180,
    rentalType: "saisonniere",
    rating: 4.9,
    reviews: 38,
    image: "/luxury-villa-interior-living.jpg",
    description: "Villa de luxe avec intérieur moderne et vue panoramique",
    bedrooms: 4,
    bathrooms: 3,
    amenities: ["Piscine", "Cuisine ouverte", "Terrasse", "Climatisation", "WiFi"],
  },
  {
    id: "10",
    name: "Bungalow Tropical Réunion",
    type: "bungalow",
    city: "Saint-Gilles",
    region: "La Réunion",
    address: "78 Chemin des Cocotiers, Saint-Gilles 97434",
    price: 95,
    rentalType: "saisonniere",
    rating: 4.7,
    reviews: 29,
    image: "/tropical-bungalow-bedroom.jpg",
    description: "Bungalow authentique avec charme tropical",
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Terrasse", "Jardin", "Cuisine équipée", "Ventilateur", "Vue jardin"],
  },
  {
    id: "11",
    name: "Penthouse Guadeloupe",
    type: "penthouse",
    city: "Pointe-à-Pitre",
    region: "Guadeloupe",
    address: "234 Boulevard de la Victoire, Pointe-à-Pitre 97110",
    price: 250,
    rentalType: "saisonniere",
    rating: 4.8,
    reviews: 42,
    image: "/penthouse-modern-kitchen.jpg",
    description: "Penthouse avec vue sur la mer et cuisine haut de gamme",
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Cuisine premium", "Terrasse panoramique", "Climatisation", "WiFi", "Ascenseur"],
  },
  {
    id: "12",
    name: "Gîte Montagne Suisse",
    type: "gite",
    city: "Verbier",
    region: "Suisse",
    address: "567 Route de Verbier, Verbier 1936",
    price: 160,
    rentalType: "saisonniere",
    rating: 4.6,
    reviews: 26,
    image: "/mountain-gite-fireplace.jpg",
    description: "Gîte cosy avec cheminée et vue sur les Alpes",
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Cheminée", "Cuisine rustique", "Terrasse", "Chauffage", "Vue montagne"],
  },
  {
    id: "13",
    name: "Loft Paris Marais",
    type: "loft",
    city: "Paris",
    region: "France",
    address: "345 Rue des Francs-Bourgeois, Paris 75003",
    price: 1400,
    rentalType: "longue-duree",
    rating: 4.7,
    reviews: 33,
    image: "/parisian-loft-industrial.jpg",
    description: "Loft spacieux avec poutres apparentes et grandes fenêtres",
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Poutres apparentes", "Cuisine ouverte", "Mezzanine", "Chauffage", "Ascenseur"],
  },
  {
    id: "14",
    name: "Maison Coloniale Guadeloupe",
    type: "maison",
    city: "Deshaies",
    region: "Guadeloupe",
    address: "789 Rue de la Liberté, Deshaies 97126",
    price: 140,
    rentalType: "saisonniere",
    rating: 4.8,
    reviews: 35,
    image: "/colonial-house-veranda.jpg",
    description: "Maison coloniale authentique avec véranda et jardin tropical",
    bedrooms: 4,
    bathrooms: 2,
    amenities: ["Véranda", "Jardin tropical", "Cuisine", "Terrasse", "Ventilateurs"],
  },
  {
    id: "15",
    name: "Appartement Moderne Luxembourg",
    type: "t2",
    city: "Belair",
    region: "Luxembourg",
    address: "456 Avenue de la Liberté, Belair L-1930",
    price: 950,
    rentalType: "longue-duree",
    rating: 4.6,
    reviews: 19,
    image: "/modern-apartment-bedroom.jpg",
    description: "Appartement contemporain avec finitions haut de gamme",
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Cuisine moderne", "Balcon", "Climatisation", "Parking", "WiFi"],
  },
  {
    id: "16",
    name: "Villa Bord de Mer Mayotte",
    type: "villa",
    city: "Sada",
    region: "Mayotte",
    address: "890 Rue de la Côte, Sada 97610",
    price: 200,
    rentalType: "saisonniere",
    rating: 4.9,
    reviews: 51,
    image: "/beachfront-villa-pool.jpg",
    description: "Villa luxe en bord de mer avec piscine à débordement",
    bedrooms: 5,
    bathrooms: 3,
    amenities: ["Piscine débordement", "Accès plage", "Cuisine équipée", "Terrasse", "Climatisation"],
  },
];

// Fonction principale
async function main() {
  console.log("🌱 Insertion des propriétés...");
  for (const prop of properties) {
  await prisma.property.upsert({
    where: { id: prop.id },
    update: {},
    create: {
      ...prop,
      amenities: JSON.stringify(prop.amenities),
    },
  });
}
  console.log("👤 Création de l’utilisateur admin...");

  const hashedPassword = bcrypt.hashSync("Admin1234!", 10);

  // Vérifie si l'admin existe déjà
  const existingUser = await prisma.user.findUnique({
    where: { email: "admin@example.com" },
  });

  if (!existingUser) {
    await prisma.user.create({
      data: {
        name: "Admin",
        email: "admin@example.com",
        password: hashedPassword,
        role: "admin",
      },
    });
    console.log("✅ Utilisateur admin créé !");
  } else {
    console.log("ℹ️ L’utilisateur admin existe déjà.");
  }

  console.log("🚀 Seed terminé !");
}

// 🧠 Exécution
main()
  .catch((e) => {
    console.error("❌ Erreur :", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });